sudo: required
dist: trusty

cache:
  - apt

language: node_js
node_js:
  - "4.2.3"

script:
  - npm test

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: "caigesn@gmail.com"
  on:
    tags: true
